version: '3.8'

services:
  api:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/gridwars
    ports:
      - "8052:8000"  
    

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gridwars
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql 
    

  frontend:
    build: ./frontend
    ports:
      - "8051:80" 
      
volumes:
  db_data: